name: Wake Streamlit App

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: curl --fail --max-time 60 --max-redirs 100 https://mdc-cbt.streamlit.app/
